services:
  - type: web
    name: arima-financial-dashboard
    env: python
    plan: free
    buildCommand: bash render-build.sh
    startCommand: bash render-start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"